/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_cognito_identity_pool_id:
    "ap-south-1:696919d2-28a3-4153-879f-a710d3f6e84a",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_R1CSsYHc7",
  aws_user_pools_web_client_id: "3cq4o83br4o8rl8tfk0ce3a6hs",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL", "PHONE_NUMBER"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint:
    "https://plqjzu6dufgjvdyt4iivhvqria.appsync-api.ap-south-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-south-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-25gr5govd5aqhmouyx3rrepitu",
  aws_user_files_s3_bucket:
    "qstat3efa8e716a4d4b729e4598456885d714110417-staging",
  aws_user_files_s3_bucket_region: "ap-south-1",
};

export default awsmobile;
